config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'beers#index'

  resources :beers

end

app/models/beer.rb
class Beer < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :beers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
	# list  all the Beers
	def index
		@beers = Beer.all
	end
#  show data for one beer
	def show
		@beer = Beer.find(params[:id])

	end
#  Displays from for creating a new beet
	def new
		@beer = Beer.new
	end
	#  displays form for editing an existing beer
	def edit
		@beer = Beer.find(params[:id])
	end
#  processes data from the new beer from and create a beer
	def create
    @beer = Beer.new(beer_params.merge(:user_id => @current_user.id))
    
    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: 'beer was successfully created.' }
        else
        format.html{ render :new}
    	end
    end
  end

# processes data from the edit beer from and updates the beer
	def update
		respond_to do |format|
		  if @beer.update(beer_params)
		    format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
		    format.json { render :show, status: :ok, location: @beer}
		  else
		    format.html { render :edit }
		    format.json { render json: @beer.errors, status: :unprocessable_entity }
		  end
		end
  	end

	# DELETE /beers/1
	# DELETE //1.json
	def destroy
		@beer.destroy
		respond_to do |format|
	 		format.html { redirect_to beers_url, notice: 'Beer was successfully destroyed.' }
	 		format.json { head :no_content }
		end
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Never trust parameters from the scary Internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:brewer, :name, :beer_type, :abv, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created. Please add your favorite Beer' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    #http://edgeguides.rubyonrails.org/active_record_migrations.html#changing-columns Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary Internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:password, :user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this  from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brewer %><br>
    <%= f.text_field :brewer  %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
<div class="field">
    <%= f.label :beer_type %><br>
    <%= f.text_field :beer_type %>
  </div>
  <div class="field">
    <%= f.label :abv %><br>
    <%= f.text_field :abv %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing Beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', @beers_path %> | <%= link_to 'Destroy', beer, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/beers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Brewer</th>
      <th>Beer Type</th>
      <th>abv</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beers.each do |beer| %>
      <tr>
        <td><%= beer.name %></td>
        <td><%= beer.brewer %></td>
        <td><%= beer.beer_type %></td>
        <td><%= beer.abv %></td>
        <td><%= @user_id %></td>
        <td><%= link_to 'Show', beer %></td>
        <td><%= link_to 'Edit', edit_beer_path(beer) %></td>
        <td><%= link_to 'Destroy', beer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer', new_beer_path %>

app/views/beers/new.html.erb
<h1> New Beer </h1>

<%= render 'form' %>


<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<!-- <p id="notice"><%= @beer.inspect %></p> -->

	<p id="notice"><%= notice %></p>

<p>
	<strong>Brewer:</strong>
	<%= @beer.brewer %>
</p>

<p>
	<strong>name:</strong>
	<%= @beer.name %>
</p>

<p>
	<strong>beer_type:</strong>
	<%= @beer.beer_type %>
</p>
<p>
	<strong>abv:</strong>
	<%= @beer.abv %>
</p>
<p>
	<strong>User:</strong>
	<%= @user_id %>
</p>

<%= link_to 'Edit', edit_beer_path(@beer) %> |
<%= link_to 'Show List', beers_path %> | 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeerApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div type="password" class="password">
    <%= f.label :password %><br>
    <%= f.text_field :password %> 
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Password</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.password %></td>
        <td><%= user.user %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>User:</strong>
  <%= @user.user %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> | <%= link_to 'Add Your Beer', new_beer_path %>